export enum AutomationExecutionStatus {
  DRAFT = 'DRAFT',
  PENDING_REVIEW = 'PENDING_REVIEW',
  PENDING_IMPLEMENTATION = 'PENDING_IMPLEMENTATION',
  EXECUTABLE = 'EXECUTABLE',
  NEEDS_UPDATE = 'NEEDS_UPDATE',
  DISABLED = 'DISABLED',
}

export enum RunBatchStatus {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  ENVIRONMENT_BLOCKED = 'ENVIRONMENT_BLOCKED',
  CANCELLED = 'CANCELLED',
}

export enum RunCaseStatus {
  NOT_RUN = 'NOT_RUN',
  RUNNING = 'RUNNING',
  PASSED = 'PASSED',
  FAILED = 'FAILED',
  SKIPPED = 'SKIPPED',
  BLOCKED = 'BLOCKED',
}

export enum FailureCategory {
  PRODUCT = 'PRODUCT',
  SCRIPT = 'SCRIPT',
  ENVIRONMENT = 'ENVIRONMENT',
  TEST_DATA = 'TEST_DATA',
  NETWORK_OR_THIRD_PARTY = 'NETWORK_OR_THIRD_PARTY',
  UNKNOWN = 'UNKNOWN',
}
