export async function checkEnvironment(baseUrl:string){try{const response=await fetch(baseUrl,{signal:AbortSignal.timeout(10_000)});return {loginPageStatus:response.ok?'OK':'FAILED',conclusion:response.ok?'READY':'BLOCKED'};}catch{return {loginPageStatus:'FAILED',conclusion:'BLOCKED'};}}
export async function checkEnvironmentConfig(baseUrl:string, config:any){const login=await checkEnvironment(baseUrl);if(login.conclusion==='BLOCKED')return {...login,keyApiStatus:[]};const paths=config?.paths??[];const results=await Promise.all(paths.map(async (path:string)=>{try{return (await fetch(new URL(path,baseUrl),{signal:AbortSignal.timeout(10_000)})).ok?'OK':'FAILED';}catch{return 'FAILED';}}));return {loginPageStatus:'OK',keyApiStatus:results,conclusion:results.every(x=>x==='OK')?'READY':'BLOCKED'};}
export function classifyFailure(message:string){if(/locator|element not found/i.test(message))return 'SCRIPT';if(/HTTP 5\d\d/i.test(message))return 'ENVIRONMENT';return 'UNKNOWN';}
import { mkdirSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';
export function redactReport(value:string){return value.replace(/(token|password)=\S+/gi,'$1=[REDACTED]');}
/** evidenceRoot must be the already-validated runtime evidence directory, never its parent. */
export function storeEvidence(evidenceRoot:string,projectId:string,batchId:string,caseId:string,name:string,content:string){if(!/^[a-zA-Z0-9._-]+$/.test(name))throw Error('unsafe evidence name');const base=resolve(evidenceRoot);const target=resolve(base,projectId,batchId,caseId,name);if(relative(base,target).startsWith('..'))throw Error('escape');mkdirSync(join(base,projectId,batchId,caseId),{recursive:true});writeFileSync(target,redactReport(content));return target;}
export function cleanupEvidence(evidenceRoot:string,cutoff=Date.now()-7*24*60*60*1000){const base=resolve(evidenceRoot);const walk=(dir:string)=>{for(const entry of readdirSync(dir,{withFileTypes:true})){const file=join(dir,entry.name);if(entry.isDirectory())walk(file);else if(statSync(file).mtimeMs<cutoff)rmSync(file);}};try{walk(base);}catch{} }
