import { createServer } from 'node:http';
import { randomUUID } from 'node:crypto';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { LocalDatabase, openLocalDatabase } from '../../../packages/database/src/local-database.js';
import { evidenceDirectory } from '../../../packages/database/src/data-directory.js';
import { checkEnvironmentConfig, redactReport } from './runner.js';

const allowed = new Set(['pdf','docx','md','txt','png','jpg','jpeg']);
const MAX_BYTES=20*1024*1024;
const readJson = async (request: import('node:http').IncomingMessage) => { const body=await new Promise<string>((resolve,reject)=>{let bytes=0;const chunks:Buffer[]=[];request.on('data',(chunk:Buffer)=>{bytes+=chunk.length;if(bytes>MAX_BYTES){request.destroy();return reject(new Error('payload too large'));}chunks.push(chunk);});request.on('end',()=>resolve(Buffer.concat(chunks).toString()));request.on('error',reject);}); return body ? JSON.parse(body) : {}; };
const importRows=(format:string,content:unknown)=>{if(format==='json'){const rows=typeof content==='string'?JSON.parse(content):content;if(!Array.isArray(rows))throw Error('invalid import');return rows;}if(format==='csv'){const lines=String(content??'').trim().split(/\r?\n/);const headers=(lines.shift()??'').split(',').map(x=>x.trim());return lines.filter(Boolean).map(line=>Object.fromEntries(line.split(',').map((value,index)=>[headers[index],value.trim()])));}throw Error('unsupported format');};
const validateImport=(rows:any[])=>{const errors:any[]=[];const seen=new Set<string>();rows.forEach((row,index)=>{for(const field of ['caseCode','module','scenario'])if(!String(row[field]??'').trim())errors.push({row:index+1,message:`${field} required`});const code=String(row.caseCode??'');if(seen.has(code))errors.push({row:index+1,message:'duplicate caseCode'});seen.add(code);});return errors;};
const validateProjectImport=(database:LocalDatabase,projectId:string,rows:any[])=>{const errors=validateImport(rows);const existing=new Set(database.all<any>('SELECT case_code FROM functional_cases WHERE project_id=?',projectId).map(item=>item.case_code));rows.forEach((row,index)=>{if(existing.has(row.caseCode))errors.push({row:index+1,message:'caseCode already exists in project'});});return errors;};
export async function startApi() {
  return startApiWithDatabase(openLocalDatabase(), evidenceDirectory());
}

/** Test-only factory. Production code must call startApi() with the approved runtime root. */
export async function createTestApi(databaseFile: string, storageRoot: string) {
  return startApiWithDatabase(new LocalDatabase(databaseFile), storageRoot);
}

async function startApiWithDatabase(database: LocalDatabase, storageRoot: string) {
  database.migrate();
  database.run('CREATE TABLE IF NOT EXISTS audit_logs (id TEXT PRIMARY KEY, actor_id TEXT NOT NULL, action TEXT NOT NULL, object_id TEXT NOT NULL, created_at TEXT NOT NULL)');
  const server = createServer(async (request,response) => { try {
    const actor = String(request.headers['x-actor-id'] ?? ''); const path = request.url ?? '';
    const send=(status:number,value:unknown)=>{response.writeHead(status,{'content-type':'application/json'});response.end(JSON.stringify(value));};
    if(!actor.trim()) return send(400,{error:'x-actor-id required'});
    const scopedVersions=path.match(/^\/projects\/([^/]+)\/functional-cases\/([^/]+)\/versions$/); if(request.method==='GET' && scopedVersions){if(!database.get('SELECT id FROM functional_cases WHERE id=? AND project_id=?',scopedVersions[2],scopedVersions[1]))return send(404,{error:'not found'});return send(200,database.caseVersions(scopedVersions[2]));}
    const body = await readJson(request);
    const importPreview=path.match(/^\/projects\/([^/]+)\/functional-case-imports\/preview$/);if(importPreview&&request.method==='POST'){const project=database.get<any>('SELECT id FROM projects WHERE id=?',importPreview[1]);if(!project)return send(404,{error:'project not found'});try{const rows=importRows(body.format,body.content);const errors=validateProjectImport(database,project.id,rows);return send(200,{valid:errors.length===0,rows,errors});}catch{return send(400,{error:'invalid import'});}}
    const importConfirm=path.match(/^\/projects\/([^/]+)\/functional-case-imports\/confirm$/);if(importConfirm&&request.method==='POST'){const project=database.get<any>('SELECT id,status FROM projects WHERE id=?',importConfirm[1]);if(!project)return send(404,{error:'project not found'});if(project.status==='ARCHIVED')return send(409,{error:'archived'});const rows:any[]=Array.isArray(body.rows)?body.rows:[];const errors=validateProjectImport(database,project.id,rows);if(!rows.length||errors.length)return send(400,{error:'invalid import rows',errors});for(const row of rows)database.createFunctionalCase(project.id,{...row,priority:row.priority??'P2',testType:row.testType??'FUNCTION',automationRecommendation:row.automationRecommendation===true},actor,'HUMAN_CREATE');database.run('INSERT INTO audit_logs VALUES (?,?,?,?,?)',randomUUID(),actor,'CONFIRM_FUNCTIONAL_IMPORT',project.id,new Date().toISOString());return send(201,{created:rows.length,status:'DRAFT'});}
    const exportCases=path.match(/^\/projects\/([^/]+)\/functional-cases\/export$/);if(exportCases&&request.method==='GET'){const project=database.get<any>('SELECT id FROM projects WHERE id=?',exportCases[1]);if(!project)return send(404,{error:'project not found'});return send(200,database.all<any>("SELECT case_code AS caseCode,module,scenario,precondition,steps,expected_result AS expectedResult,priority,test_type AS testType,current_version_no AS versionNo FROM functional_cases WHERE project_id=? AND status='CONFIRMED' ORDER BY case_code",project.id));}
    const metrics=path.match(/^\/projects\/([^/]+)\/metrics$/);if(metrics&&request.method==='GET'){const project=database.get<any>('SELECT id FROM projects WHERE id=?',metrics[1]);if(!project)return send(404,{error:'project not found'});const count=(sql:string,...args:any[])=>Number(database.get<any>(sql,...args)?.count??0);const functional=count('SELECT count(*) count FROM functional_cases WHERE project_id=?',project.id);const ai=count("SELECT count(DISTINCT functional_case_id) count FROM case_change_logs WHERE project_id=? AND source='AI'",project.id);const modified=count("SELECT count(DISTINCT functional_case_id) count FROM case_change_logs WHERE project_id=? AND source='HUMAN_EDIT'",project.id);const rejected=count("SELECT count(*) count FROM automation_cases WHERE project_id=? AND review_status='REJECTED'",project.id);const automation=count("SELECT count(*) count FROM functional_cases f WHERE project_id=? AND EXISTS (SELECT 1 FROM automation_cases a WHERE a.functional_case_id=f.id AND a.project_id=f.project_id)",project.id);const needsUpdate=count("SELECT count(*) count FROM automation_cases WHERE project_id=? AND execution_status='NEEDS_UPDATE'",project.id);const passed=count("SELECT count(*) count FROM run_case_results WHERE project_id=? AND final_status='PASSED'",project.id);const blocked=count("SELECT count(*) count FROM run_case_results WHERE project_id=? AND final_status='BLOCKED'",project.id);const trend=database.all<any>("SELECT substr(started_at,1,10) AS date,count(*) AS failures FROM run_attempts WHERE project_id=? AND status='FAILED' GROUP BY substr(started_at,1,10) ORDER BY date",project.id);return send(200,{functional:{total:functional},aiAdoption:{numerator:ai,denominator:functional},manualModification:{numerator:modified,denominator:functional},rejection:{numerator:rejected,denominator:count('SELECT count(*) count FROM automation_cases WHERE project_id=?',project.id)},automationAdoption:{numerator:automation,denominator:functional},needsUpdate:{numerator:needsUpdate,denominator:count('SELECT count(*) count FROM automation_cases WHERE project_id=?',project.id)},execution:{passed,blocked},failureTrend:trend,p0Coverage:{numerator:0,denominator:0}});}
    const newCase=path.match(/^\/projects\/([^/]+)\/functional-cases$/);
    if(request.method==='POST' && newCase){ const project=database.get<{id:string;status:string}>('SELECT id,status FROM projects WHERE id=?',newCase[1]);if(!project)return send(404,{error:'project not found'});if(project.status==='ARCHIVED')return send(409,{error:'archived'});try{const item=database.createFunctionalCase(project.id,body,actor);database.run('INSERT INTO audit_logs VALUES (?,?,?,?,?)',randomUUID(),actor,'CREATE_FUNCTIONAL_CASE',item.id,new Date().toISOString());return send(201,item);}catch{return send(409,{error:'duplicate case'});}}
    const generation=path.match(/^\/requirements\/([^/]+)\/generations$/);
    if(request.method==='POST' && generation){const snapshot=database.get<{project_id:string}>('SELECT project_id FROM requirement_snapshots WHERE id=?',generation[1]);if(!snapshot)return send(404,{error:'snapshot not found'});const candidate=body.candidate;if(!candidate||!candidate.caseCode||!candidate.module||!candidate.scenario||!Array.isArray(candidate.steps))return send(400,{error:'invalid AI candidate'});const item=database.createFunctionalCase(snapshot.project_id,candidate,actor,'AI');database.run('INSERT INTO audit_logs VALUES (?,?,?,?,?)',randomUUID(),actor,'IMPORT_AI_DRAFT',item.id,new Date().toISOString());return send(201,{...item,status:'DRAFT'});}
    const caseAction=path.match(/^\/projects\/([^/]+)\/functional-cases\/([^/]+)\/(draft|confirm|retire)$/);
    if(caseAction){const [,projectId,caseId,action]=caseAction;if(!database.get('SELECT id FROM functional_cases WHERE id=? AND project_id=?',caseId,projectId))return send(404,{error:'not found'}); if(action==='draft'&&request.method==='PATCH'){const item=database.updateCaseDraft(caseId,body,actor);database.run('INSERT INTO audit_logs VALUES (?,?,?,?,?)',randomUUID(),actor,'EDIT_FUNCTIONAL_CASE',caseId,new Date().toISOString());return send(200,item);} if(action==='confirm'&&request.method==='POST'){try{const item=database.confirmCase(caseId,body.changeReason,actor);database.run('INSERT INTO audit_logs VALUES (?,?,?,?,?)',randomUUID(),actor,'CONFIRM_FUNCTIONAL_CASE',caseId,new Date().toISOString());return send(201,item);}catch{return send(409,{error:'cannot confirm'});}}if(action==='retire'&&request.method==='POST'){database.retireCase(caseId);database.run('INSERT INTO audit_logs VALUES (?,?,?,?,?)',randomUUID(),actor,'RETIRE_FUNCTIONAL_CASE',caseId,new Date().toISOString());return send(200,{id:caseId});}}
    const autoDraft=path.match(/^\/projects\/([^/]+)\/functional-cases\/([^/]+)\/automation-drafts$/);if(autoDraft&&request.method==='POST'){const item=database.get<any>('SELECT status FROM functional_cases WHERE id=? AND project_id=?',autoDraft[2],autoDraft[1]);if(!item)return send(404,{error:'not found'});if(item.status!=='CONFIRMED')return send(409,{error:'not confirmed'});const created=database.createAutomationDraft(autoDraft[1],autoDraft[2],body.design??{});database.run('INSERT INTO audit_logs VALUES (?,?,?,?,?)',randomUUID(),actor,'CREATE_AUTOMATION_DRAFT',created.id,new Date().toISOString());return send(201,created);}
    const impacts=path.match(/^\/projects\/([^/]+)\/functional-cases\/([^/]+)\/impacts$/);if(impacts&&request.method==='GET')return send(200,database.impacts(impacts[1],impacts[2]));
    const submit=path.match(/^\/projects\/([^/]+)\/automation-cases\/([^/]+)\/submit$/);if(submit&&request.method==='POST'){try{database.submitAutomation(submit[2],submit[1]);database.run('INSERT INTO audit_logs VALUES (?,?,?,?,?)',randomUUID(),actor,'SUBMIT_AUTOMATION_REVIEW',submit[2],new Date().toISOString());return send(200,{id:submit[2]});}catch{return send(409,{error:'invalid transition'});}}
    const review=path.match(/^\/projects\/([^/]+)\/automation-cases\/([^/]+)\/review$/);if(review&&request.method==='POST'){try{database.reviewAutomation(review[2],review[1],body.approved===true);database.run('INSERT INTO audit_logs VALUES (?,?,?,?,?)',randomUUID(),actor,'REVIEW_AUTOMATION',review[2],new Date().toISOString());return send(200,{id:review[2]});}catch{return send(409,{error:'invalid review'});}}
    const script=path.match(/^\/projects\/([^/]+)\/automation-cases\/([^/]+)\/script-version$/);if(script&&request.method==='POST'){try{database.linkScript(script[2],script[1],body.path,body.sha);database.run('INSERT INTO audit_logs VALUES (?,?,?,?,?)',randomUUID(),actor,'LINK_AUTOMATION_SCRIPT',script[2],new Date().toISOString());return send(201,{id:script[2],executionStatus:'EXECUTABLE'});}catch{return send(409,{error:'invalid script'});}}
    const batch=path.match(/^\/projects\/([^/]+)\/run-batches$/);if(batch&&request.method==='POST'){try{const created=database.createRunBatch(batch[1],body.environmentId,body.selection??'ALL',body.selectedIds??[],actor,body.testSuiteId);database.run('INSERT INTO audit_logs VALUES (?,?,?,?,?)',randomUUID(),actor,'CREATE_RUN_BATCH',created.id,new Date().toISOString());return send(201,created);}catch{return send(400,{error:'invalid batch'});}}
    const start=path.match(/^\/projects\/([^/]+)\/run-batches\/([^/]+)\/start$/);if(start&&request.method==='POST'){const batchInfo=database.get<any>('SELECT execution_snapshot FROM run_batches WHERE id=? AND project_id=?',start[2],start[1]);if(!batchInfo)return send(404,{error:'not found'});const env=JSON.parse(batchInfo.execution_snapshot).environment;const healthResult=await checkEnvironmentConfig(env.baseUrl,env.healthCheckConfig);database.recordHealth(start[1],start[2],healthResult);return send(200,healthResult);}
    const ingest=path.match(/^\/projects\/([^/]+)\/run-batches\/([^/]+)\/results$/);if(ingest&&request.method==='POST'){try{const item=database.ingestAttempt(ingest[1],ingest[2],body.automationCaseVersionId,body.status,redactReport(String(body.error??'')));database.run('INSERT INTO audit_logs VALUES (?,?,?,?,?)',randomUUID(),actor,'INGEST_RUN_RESULT',ingest[2],new Date().toISOString());return send(201,item);}catch{return send(409,{error:'invalid result'});}}
    if(request.method==='POST' && path==='/projects') { if(!/^[A-Z0-9-]+$/.test(body.code)) return send(400,{error:'invalid code'}); try {const p=database.createProject(body.code,body.name); database.run('INSERT INTO audit_logs VALUES (?,?,?,?,?)',randomUUID(),actor,'CREATE_PROJECT',p.id,new Date().toISOString());return send(201,p);}catch{return send(409,{error:'duplicate project'});} }
    const match=path.match(/^\/projects\/([^/]+)\/(environments|requirements)$/); if(!match) return send(404,{error:'not found'}); const [,,kind]=match;
    const row=database.get<{id:string;status:string}>('SELECT id,status FROM projects WHERE id=?',match[1]); if(!row)return send(404,{error:'project not found'}); if(row.status==='ARCHIVED')return send(409,{error:'archived'});
    if(kind==='environments'){const id=randomUUID();database.run('INSERT INTO environments (id,project_id,name,base_url,health_check_config,secret_ref,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)',id,row.id,body.name,body.baseUrl,JSON.stringify(body.healthCheckConfig??{}),'local/ref',new Date().toISOString(),new Date().toISOString());database.run('INSERT INTO audit_logs VALUES (?,?,?,?,?)',randomUUID(),actor,'CREATE_ENVIRONMENT',id,new Date().toISOString());return send(201,{id});}
    const ext=String(body.fileName).split('.').pop()?.toLowerCase(); if(!ext || !allowed.has(ext))return send(400,{error:'invalid file'}); const id=randomUUID();const key=join(row.id,id,body.fileName.replace(/[^a-zA-Z0-9._-]/g,'_'));const target=join(storageRoot ?? evidenceDirectory(), 'requirements',key);mkdirSync(dirname(target),{recursive:true});writeFileSync(target,body.content);database.run('INSERT INTO requirement_snapshots (id,project_id,file_name,object_key,manual_version,summary,uploaded_by,uploaded_at) VALUES (?,?,?,?,?,?,?,?)',id,row.id,body.fileName,key,null,null,actor,new Date().toISOString());database.run('INSERT INTO audit_logs VALUES (?,?,?,?,?)',randomUUID(),actor,'UPLOAD_REQUIREMENT',id,new Date().toISOString());return send(201,{id,objectKey:key});
  } catch (error) { response.writeHead((error as Error).message==='payload too large'?413:500).end(); }});
  await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve)); const address=server.address() as import('node:net').AddressInfo;
  return {url:`http://127.0.0.1:${address.port}`,stop:async()=>{await new Promise<void>(resolve=>server.close(()=>resolve()));database.close();}};
}
