import { randomUUID } from 'node:crypto';
import { mkdirSync, readFileSync } from 'node:fs';
import { dirname, join, posix } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { databasePath } from './data-directory.js';

const migrationPath = join(import.meta.dirname, '..', 'migrations', '001_init.sql');
const now = () => new Date().toISOString();

export class LocalDatabase {
  private readonly db: DatabaseSync;

  constructor(path: string) {
    mkdirSync(dirname(path), { recursive: true });
    this.db = new DatabaseSync(path);
    this.db.exec('PRAGMA foreign_keys = ON');
  }

  migrate() {
    this.db.exec('CREATE TABLE IF NOT EXISTS schema_migrations (id TEXT PRIMARY KEY, applied_at TEXT NOT NULL)');
    const applied = this.db.prepare('SELECT id FROM schema_migrations WHERE id=?').get('001_init');
    if (applied) return;
    this.db.exec('BEGIN IMMEDIATE');
    try { this.db.exec(readFileSync(migrationPath, 'utf8')); this.db.prepare('INSERT INTO schema_migrations (id,applied_at) VALUES (?,?)').run('001_init', now()); this.db.exec('COMMIT'); }
    catch (error) { this.db.exec('ROLLBACK'); throw error; }
  }
  close() { this.db.close(); }
  createProject(code: string, name: string) {
    const id = randomUUID(); const timestamp = now();
    this.db.prepare('INSERT INTO projects (id,code,name,created_at,updated_at) VALUES (?,?,?,?,?)').run(id, code, name, timestamp, timestamp);
    return { id, code, name };
  }
  createFunctionalCase(projectId:string, input:any, actor:string, source='HUMAN_CREATE') { const id=randomUUID(), timestamp=now(); this.run('INSERT INTO functional_cases (id,project_id,case_code,module,scenario,precondition,steps,expected_result,priority,test_type,automation_recommendation,status,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',id,projectId,input.caseCode,input.module,input.scenario,input.precondition??null,JSON.stringify(input.steps??[]),input.expectedResult??'',input.priority,input.testType,input.automationRecommendation?1:0,'DRAFT',actor,timestamp,timestamp); this.run('INSERT INTO case_change_logs (id,project_id,functional_case_id,field,new_value,source,actor_id,created_at) VALUES (?,?,?,?,?,?,?,?)',randomUUID(),projectId,id,'create',JSON.stringify(input),source,actor,timestamp); return {id}; }
  updateCaseDraft(id:string,input:any,actor:string) { const current=this.get<any>('SELECT * FROM functional_cases WHERE id=?',id);if(!current)throw new Error('not found'); if(current.status==='RETIRED')throw new Error('retired'); const permitted=['module','scenario','priority','testType','automationRecommendation','precondition','steps','expectedResult'];for(const key of permitted){if(input[key]===undefined)continue;const column=key==='testType'?'test_type':key==='automationRecommendation'?'automation_recommendation':key==='expectedResult'?'expected_result':key;const value=key==='automationRecommendation'?(input[key]?1:0):key==='steps'?JSON.stringify(input[key]):input[key];this.run(`UPDATE functional_cases SET ${column}=?,status='DRAFT',updated_at=? WHERE id=?`,value,now(),id);this.run('INSERT INTO case_change_logs (id,project_id,functional_case_id,field,old_value,new_value,source,actor_id,reason,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)',randomUUID(),current.project_id,id,key,JSON.stringify(current[column]),JSON.stringify(value),'HUMAN_EDIT',actor,input.changeReason??null,now());} return {id}; }
  confirmCase(id:string,reason:string,actor:string) { const item=this.get<any>('SELECT * FROM functional_cases WHERE id=?',id);if(!item||item.status==='RETIRED')throw new Error('cannot confirm');const version=(item.current_version_no??0)+1;const timestamp=now(), versionId=randomUUID();this.run('INSERT INTO functional_case_versions (id,project_id,functional_case_id,version_no,module,scenario,precondition,steps,expected_result,priority,test_type,automation_recommendation,change_reason,confirmed_by,confirmed_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',versionId,item.project_id,id,version,item.module,item.scenario,item.precondition,item.steps,item.expected_result,item.priority,item.test_type,item.automation_recommendation,reason,actor,timestamp);this.run('UPDATE functional_cases SET current_version_no=?,status=?,updated_at=? WHERE id=?',version,'CONFIRMED',timestamp,id);if(version>1){for(const a of this.db.prepare("SELECT id FROM automation_cases WHERE functional_case_id=? AND execution_status='EXECUTABLE'").all(id) as any[]){this.run('INSERT INTO automation_impacts (id,project_id,functional_case_version_id,automation_case_id,impact_type,status,created_at) VALUES (?,?,?,?,?,?,?)',randomUUID(),item.project_id,versionId,a.id,'FUNCTIONAL_CHANGE','OPEN',timestamp);this.run('UPDATE automation_cases SET execution_status=? WHERE id=?','NEEDS_UPDATE',a.id);}}return {id,versionNo:version}; }
  caseVersions(id:string) { return (this.db.prepare('SELECT version_no as versionNo,module,scenario,precondition,steps,expected_result as expectedResult,priority,test_type as testType,automation_recommendation as automationRecommendation FROM functional_case_versions WHERE functional_case_id=? ORDER BY version_no').all(id) as any[]); }
  retireCase(id:string) { this.run('UPDATE functional_cases SET status=?,updated_at=? WHERE id=?','RETIRED',now(),id); }
  createAutomationDraft(projectId:string, functionalCaseId:string, design:any) { const id=randomUUID(), t=now();this.run('INSERT INTO automation_cases (id,project_id,case_code,functional_case_id,level,tags,review_status,execution_status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)',id,projectId,`AT-${id.slice(0,8)}`,functionalCaseId,design.level??'UI','[]','DRAFT','DRAFT',t,t);this.run('INSERT INTO automation_draft_designs VALUES (?,?,?)',id,projectId,JSON.stringify(design));return {id,executionStatus:'DRAFT'}; }
  submitAutomation(id:string,projectId:string) { const item=this.get<any>('SELECT review_status FROM automation_cases WHERE id=? AND project_id=?',id,projectId);if(!item||item.review_status!=='DRAFT')throw Error('invalid transition');this.run('UPDATE automation_cases SET review_status=?,updated_at=? WHERE id=?','PENDING_REVIEW',now(),id); }
  reviewAutomation(id:string,projectId:string,approved:boolean) { const item=this.get<any>('SELECT * FROM automation_cases WHERE id=? AND project_id=?',id,projectId);if(!item||item.review_status!=='PENDING_REVIEW')throw Error('invalid review');this.run('UPDATE automation_cases SET review_status=?,execution_status=?,updated_at=? WHERE id=?',approved?'APPROVED':'REJECTED',approved?'PENDING_IMPLEMENTATION':'DRAFT',now(),id); }
  linkScript(id:string,projectId:string,path:string,sha:string) { const item=this.get<any>('SELECT * FROM automation_cases WHERE id=? AND project_id=?',id,projectId);if(!item||item.review_status!=='APPROVED'||/[\\:]/.test(path)||path.startsWith('/')||!/^([a-f0-9]{40})$/i.test(sha))throw Error('invalid script');let repo=this.get<any>('SELECT id,script_root FROM project_repositories WHERE project_id=?',projectId);if(!repo){const rid=randomUUID();this.run('INSERT INTO project_repositories VALUES (?,?,?,?,?,?,?,?)',rid,projectId,'local://test','main','tests','test','1',now());repo={id:rid,script_root:'tests'};}const root=posix.normalize(repo.script_root);const candidate=posix.normalize(path);if(!(candidate===root||candidate.startsWith(`${root}/`)))throw Error('outside root');const source=this.get<any>('SELECT id FROM functional_case_versions WHERE functional_case_id=? ORDER BY version_no DESC',item.functional_case_id);const design=this.get<any>('SELECT design FROM automation_draft_designs WHERE automation_case_id=? AND project_id=?',id,projectId)?.design??'{}';this.run('INSERT INTO automation_case_versions (id,project_id,automation_case_id,version_no,functional_case_version_id,project_repository_id,design,script_path,git_sha,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)',randomUUID(),projectId,id,(item.current_version_no??0)+1,source.id,repo.id,design,candidate,sha,now());this.run('UPDATE automation_cases SET execution_status=?,current_version_no=?,updated_at=? WHERE id=?','EXECUTABLE',(item.current_version_no??0)+1,now(),id); }
  impacts(projectId:string,caseId:string){return this.db.prepare('SELECT i.status,i.impact_type as impactType,a.id as automationCaseId FROM automation_impacts i JOIN automation_cases a ON a.id=i.automation_case_id WHERE i.project_id=? AND a.functional_case_id=?').all(projectId,caseId);}
  createRunBatch(projectId:string,environmentId:string,selection:string,selectedIds:string[],actor:string,suiteId?:string){if(!['ALL','SUITE','SELECTED'].includes(selection))throw Error('selection');const env=this.get<any>('SELECT * FROM environments WHERE id=? AND project_id=?',environmentId,projectId);if(!env)throw Error('environment');let cases=this.db.prepare('SELECT * FROM automation_cases WHERE project_id=?').all(projectId) as any[];if(selection==='SUITE'){if(!suiteId||!this.get('SELECT id FROM test_suites WHERE id=? AND project_id=?',suiteId,projectId))throw Error('suite');const memberIds=(this.db.prepare('SELECT automation_case_id FROM test_suite_members WHERE test_suite_id=? AND project_id=?').all(suiteId) as any[]).map(x=>x.automation_case_id);cases=cases.filter(x=>memberIds.includes(x.id));}if(selection==='SELECTED'){if(!Array.isArray(selectedIds)||selectedIds.length===0)throw Error('selected');const found=cases.filter(x=>selectedIds.includes(x.id));if(found.length!==selectedIds.length||found.some(x=>x.execution_status!=='EXECUTABLE'))throw Error('selected unavailable');cases=found;}const selected:any[]=[],excluded:any[]=[];for(const item of cases){if(item.execution_status!=='EXECUTABLE'){excluded.push({id:item.id,code:item.case_code,reason:item.execution_status});continue;}const ver=this.get<any>('SELECT * FROM automation_case_versions WHERE automation_case_id=? ORDER BY version_no DESC',item.id);selected.push({automationCaseId:item.id,code:item.case_code,automationCaseVersionId:ver.id,functionalCaseVersionId:ver.functional_case_version_id,scriptPath:ver.script_path,scriptSha:ver.git_sha});}const snapshot={selected,excluded,maxRetries:1,environment:{id:env.id,baseUrl:env.base_url,healthCheckConfig:JSON.parse(env.health_check_config)}};const id=randomUUID();this.run('INSERT INTO run_batches (id,project_id,environment_id,trigger_type,triggered_by,status,selection_snapshot,execution_snapshot,created_at) VALUES (?,?,?,?,?,?,?,?,?)',id,projectId,environmentId,selection,actor,'PENDING',JSON.stringify(snapshot),JSON.stringify(snapshot),now());return {id,selectionSnapshot:snapshot};}
  ingestAttempt(projectId:string,batchId:string,caseVersionId:string,status:string,error=''){const batch=this.get<any>('SELECT * FROM run_batches WHERE id=? AND project_id=?',batchId,projectId);if(!batch||batch.status==='ENVIRONMENT_BLOCKED')throw Error('batch');let result=this.get<any>('SELECT * FROM run_case_results WHERE run_batch_id=? AND automation_case_version_id=?',batchId,caseVersionId);if(!result){const snap=(JSON.parse(batch.execution_snapshot).selected as any[]).find(x=>x.automationCaseVersionId===caseVersionId);if(!snap)throw Error('snapshot');const id=randomUUID();this.run('INSERT INTO run_case_results (id,project_id,run_batch_id,automation_case_version_id,functional_case_version_id,case_snapshot,script_sha,final_status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)',id,projectId,batchId,caseVersionId,snap.functionalCaseVersionId,JSON.stringify(snap),snap.scriptSha,'NOT_RUN',now(),now());result={id};}const count=(this.get<any>('SELECT count(*) c FROM run_attempts WHERE run_case_result_id=?',result.id).c as number);const previous=this.get<any>('SELECT status FROM run_attempts WHERE run_case_result_id=? ORDER BY attempt_no DESC',result.id);if(count>=2||(count===1&&previous.status!=='FAILED'))throw Error('max retries');this.run('INSERT INTO run_attempts (id,project_id,run_case_result_id,attempt_no,status,started_at,finished_at,error_summary) VALUES (?,?,?,?,?,?,?,?)',randomUUID(),projectId,result.id,count+1,status,now(),now(),error);this.run('UPDATE run_case_results SET final_status=?,error_summary=?,updated_at=? WHERE id=?',status,error,result.id);if(!this.get('SELECT id FROM failure_triage WHERE run_case_result_id=? AND confirmed_category IS NOT NULL',result.id))this.run('INSERT OR REPLACE INTO failure_triage (id,project_id,run_case_result_id,ai_category,summary) VALUES (?,?,?,?,?)',randomUUID(),projectId,result.id,error.includes('locator')?'SCRIPT':error.includes('500')?'ENVIRONMENT':'UNKNOWN',error);return {attempt:count+1,status};}
  blockBatch(projectId:string,batchId:string){this.run('UPDATE run_batches SET status=?,finished_at=? WHERE id=? AND project_id=?','ENVIRONMENT_BLOCKED',now(),batchId,projectId);}
  recordHealth(projectId:string,batchId:string,health:any){this.run('INSERT OR REPLACE INTO environment_health (id,project_id,run_batch_id,login_page_status,key_api_status,conclusion,checked_at) VALUES (?,?,?,?,?,?,?)',randomUUID(),projectId,batchId,health.loginPageStatus,JSON.stringify(health.keyApiStatus??[]),health.conclusion,now());if(health.conclusion==='BLOCKED')this.blockBatch(projectId,batchId);}
  seedDemo() {
    const project = this.projectByCode('DEMO') ?? this.createProject('DEMO', 'Demo project');
    const timestamp = now();
    this.db.prepare("INSERT OR IGNORE INTO environments (id,project_id,name,base_url,health_check_config,secret_ref,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)").run(randomUUID(), project.id, 'test', 'http://127.0.0.1', '{"paths":[]}', 'local/demo/test', timestamp, timestamp);
    this.db.prepare("INSERT OR IGNORE INTO test_suites (id,project_id,name,selection_rule,created_at) VALUES (?,?,?,?,?)").run(randomUUID(), project.id, 'smoke', '{"tags":["smoke"]}', timestamp);
  }
  projectByCode(code: string): { id: string; code: string; name: string } | undefined { return this.db.prepare('SELECT id,code,name FROM projects WHERE code=?').get(code) as { id: string; code: string; name: string } | undefined; }
  environment(code: string, name: string) { return this.db.prepare('SELECT e.* FROM environments e JOIN projects p ON p.id=e.project_id WHERE p.code=? AND e.name=?').get(code, name); }
  testSuite(code: string, name: string) { return this.db.prepare('SELECT s.* FROM test_suites s JOIN projects p ON p.id=s.project_id WHERE p.code=? AND s.name=?').get(code, name); }
  tableColumns(table: string): string[] { return (this.db.prepare(`PRAGMA table_info(${table})`).all() as { name: string }[]).map((column) => column.name); }
  run(sql: string, ...values: any[]) { return this.db.prepare(sql).run(...values); }
  get<T>(sql: string, ...values: any[]): T | undefined { return this.db.prepare(sql).get(...values) as T | undefined; }
  appliedMigrations(): string[] { return (this.db.prepare('SELECT id FROM schema_migrations ORDER BY id').all() as { id: string }[]).map((row) => row.id); }
  insertCrossProjectVersion() {
    const demo = this.projectByCode('DEMO')!; const other = this.projectByCode('OTHER')!; const timestamp = now();
    this.db.prepare('INSERT INTO functional_cases (id,project_id,case_code,module,scenario,priority,test_type,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)').run('case-a', demo.id, 'TC-A', 'M', 'S', 'P0', 'FUNCTION', 'test', timestamp, timestamp);
    this.db.prepare('INSERT INTO functional_case_versions (id,project_id,functional_case_id,version_no,module,scenario,steps,expected_result,priority,test_type,automation_recommendation,change_reason,confirmed_by,confirmed_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run('bad', other.id, 'case-a', 1, 'M', 'S', '[]', 'ok', 'P0', 'FUNCTION', 0, 'test', 'test', timestamp);
  }
  createCaseVersions(projectCode: string, caseCode: string, module: string, firstScenario: string, secondScenario: string): string[] {
    const project = this.projectByCode(projectCode)!; const id = randomUUID(); const timestamp = now();
    this.db.prepare('INSERT INTO functional_cases (id,project_id,case_code,module,scenario,priority,test_type,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)').run(id,project.id,caseCode,module,firstScenario,'P0','FUNCTION','test',timestamp,timestamp);
    const insert = this.db.prepare('INSERT INTO functional_case_versions (id,project_id,functional_case_id,version_no,module,scenario,steps,expected_result,priority,test_type,automation_recommendation,change_reason,confirmed_by,confirmed_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)');
    insert.run(randomUUID(),project.id,id,1,module,firstScenario,'[]','ok','P0','FUNCTION',0,'v1','test',timestamp);
    this.db.prepare('UPDATE functional_cases SET scenario=? WHERE id=?').run(secondScenario,id);
    insert.run(randomUUID(),project.id,id,2,module,secondScenario,'[]','ok','P0','FUNCTION',0,'v2','test',timestamp);
    return (this.db.prepare('SELECT scenario FROM functional_case_versions WHERE functional_case_id=? ORDER BY version_no').all(id) as { scenario:string }[]).map(row=>row.scenario);
  }
}

/** Production entry point: opens only the validated configured database path. */
export function openLocalDatabase(environment = process.env): LocalDatabase { return new LocalDatabase(databasePath(environment)); }
